stages:
  - build-job
  - build


build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - runner
  image: openjdk:16
  script:
    - ./gradlew bootWar
  artifacts:
    paths:
      - ./build/libs/app.war

build:
  tags:
    - runner
  image: docker:latest
  stage: build
  script:
    - ./gradlew bootWar
    - echo hi
    - docker build -t kakaotest:0.1 .