stages:
  - build-job
  - build
  - deploy


build-job: # This job runs in the build stage, which runs first.
  stage: build-job
  tags:
    - runner
  image: openjdk:16
  script:
    - ./gradlew bootWar
  cache:
    key: whenever-with-dependencies
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    paths:
      - ./build/libs/app.war

build:
  tags:
    - runner
  image: docker:latest
  stage: build
  script:
    - echo hi
    - docker login -u tim0726 -p minseo0726
    - docker build --platform linux/amd64 -t tim0726/kakaotest:0.1 .
    - docker push tim0726/kakaotest:0.1
    #docker run --name kakaotest -p 8080:8080 --link mariadb kakaotest:0.1
deploy-image:
  tags:
    - runner
  stage: deploy
  before_script:
    - 'which ssh-agent || (apk update && apk add openssh-client)'
    - eval $(ssh-agent -s)
    - echo -e -----BEGIN OPENSSH PRIVATE KEY-----\n
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
      NhAAAAAwEAAQAAAYEAvo2QiCgy5Xayf+ffNth+HWgySFvuwyz0luw+pSHJbFMDKrHPNE0p
      Tai5kRdVXuqArqKCNFjYggUXe6P5pmmCpCr4Ur6tYgtzUVeDKM5nrYQNDlFl1q10UO6/wX
      JFhmZlu3RpezHvyU7vjri69honErfr+COzG7NZjCahvzAjSezPQ+WOGuJwCGL5GB0s9DZC
      iFDicYruq31CODZiJL6vldwDPRxbvgT0FmgsyzGWYVuFsgUZG/IDgBrMmpTfDxxNtUjRMO
      XI6qnl/l/2eRdYsWPAKCgdYbaF3Vv3eVxldZanAY+JMq7R9hBV4sBLgoxijFFbwpeugOMK
      nMZ4SL0Nv4HjPkJBa29zmDD95tSCSBa1XJPcuHf/udBXTavcehnQCMTaY1u/EXzVqBSVCT
      1fkfUHp9gInckincOA8Yo5RT8juoxWac53QZFfyEFHgNf/HWJ7Uklz0l/mbCkedkgVEZXr
      tBvp3RtDFTFK70FjMWKDRWojLSV1OInB5dLMKTOzAAAFkHbin+524p/uAAAAB3NzaC1yc2
      EAAAGBAL6NkIgoMuV2sn/n3zbYfh1oMkhb7sMs9JbsPqUhyWxTAyqxzzRNKU2ouZEXVV7q
      gK6igjRY2IIFF3uj+aZpgqQq+FK+rWILc1FXgyjOZ62EDQ5RZdatdFDuv8FyRYZmZbt0aX
      sx78lO7464uvYaJxK36/gjsxuzWYwmob8wI0nsz0PljhricAhi+RgdLPQ2QohQ4nGK7qt9
      Qjg2YiS+r5XcAz0cW74E9BZoLMsxlmFbhbIFGRvyA4AazJqU3w8cTbVI0TDlyOqp5f5f9n
      kXWLFjwCgoHWG2hd1b93lcZXWWpwGPiTKu0fYQVeLAS4KMYoxRW8KXroDjCpzGeEi9Db+B
      4z5CQWtvc5gw/ebUgkgWtVyT3Lh3/7nQV02r3HoZ0AjE2mNbvxF81agUlQk9X5H1B6fYCJ
      3JIp3DgPGKOUU/I7qMVmnOd0GRX8hBR4DX/x1ie1JJc9Jf5mwpHnZIFRGV67Qb6d0bQxUx
      Su9BYzFig0VqIy0ldTiJweXSzCkzswAAAAMBAAEAAAGAUkf4sAKDr7fobfim1xz2oCYdCE
      fCOr8PwpeymUWUn1TdGjN7YH8tJZ6EupUTxQ+Hj2EWzhnLK6GdOUNeCrCmu9LeNYSmg56k
      Jeye8yDlffR2WsdlLSTrBAOEA7kfMmDG7wHehlbSzt9p6/vyp1A1rQyENTrdHUn9kdogn9
      jedA5wlUXrbcp3S/fIzdPTVISViB09GoA+fQhybql1CZ7ZXOGK+HllWBD1gTNsnDUGVXXa
      rjsrU3jWcBuiW+GKzBCQ8pr6qVGoC6dzindAv3HHWhBAAuaVh/XZVjrd5b59Yu0sFDGqMr
      rvX83XzSCSq4BiBopbbWVVbCfN1UuNDFuKyk2eKOvZgGKKOjOlZhSKSZk2lIiA9tyXw5gg
      1C2rLdZf6PJhtJnoSiE9zSZ/mkmKouZUC3azgAfYN1vhmdsje6oTZjf1lkGFasZMqfw9oL
      MFOc+/YCSumLpf2gukfx84G78IKfOF/3gr4jDQJf1PyuJRo9Ta4g/ghK6l6ilxIxchAAAA
      wQDdK8i+1chc8q8gVKwPr7XMPB4jKGXbAU7tCOkVId3FIkLwbKK9U5lRqJnY1HbAuu0tA4
      51viUa0KrlS7t+dQWdHZSMhpIi1OkLY1AewZOIROYBEgKFUY4EpgePS/G0bFJUoAld/Nw+
      t6UaoM8ceWBOWNwAWOFbMwrQESVgcGkd+M/PntPR4nyRZLe/wxYuMRHGznYbCPymG7vbUY
      T91S32IriOKLG8G0GQZnmUl0DYpuzE5MkgNNsy2tyEnfM3hTYAAADBAOaAqUHl2lazoA4a
      1eW6agE6NuFv5wZVuM+/s8sNEOPciMct0bS01Sb0heErmTlYiqIAXqz4fhXB1fIBRxi+zv
      xtEu3TN8J8C/TNP/SXEMupKSnRWSFaBDotoD5I9NMBAjYbN5Ea8aqY4okgS1pF/T/dWONe
      bIBqIT5VHXzzKS2fL/oFWbKgK7Ms1+o1i+9zr74NnQpYGSesTPg4xkdlq64UWfnz8RBHJT
      0/6tSYEgCm0yVTWJwIjqr4Js7v6easowAAAMEA06Gd1KwY1InqVkAWKDbiuvw0a8bWEp2b
      c6sd/2pE19SYrxSqj7lcMfIxu6+jVPGu8gwlmtkkHsSpol8zmDgBEWZsw6o0mbUdprhDx2
      8FwxDLdgbq1PhqrOUerFNJrrMk+w0xdnt8hN1rPhtaDyLC9TS0HZ6AM04fcNE1zSVwVlHB
      eGXztmuDnPpS3y+/1ErF7NMB8T4yBv3hzREvv544CquuLYROtmRv9lBbp7l8GqHUPJSLvc
      kU7+i75JFY4z2xAAAAF21pbnNlb0BtYWMtbWluc2VvLmxvY2FsAQID\n
      -----END OPENSSH PRIVATE KEY----- | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p 22 218.209.10.162 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh dorika@218.209.10.162