stages:
  - build

build:
  stage: build
  script:
    - echo hi
    - apt-get install curl
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    - sudo apt-get install docker-ce docker-ce-cli containerd.io
    - sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
    - docker-compose up
  tags:
    - runner
