stages:
  - build
variables:
  DOCKER_HOST: tcp://gitlab-dind:2375
build:
  tags:
    - runner
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - echo hi
    - docker build -t kakaotest:0.1 .
