stages:
  - build-job
  - build


build-job: # This job runs in the build stage, which runs first.
  stage: build-job
  tags:
    - runner
  image: openjdk:16
  script:
    - ./gradlew bootWar
  cache:
    key: whenever-with-dependencies
    paths:
      - .gradle/wrapper
      - .gradle/caches


  artifacts:
    paths:
      - ./build/libs/app.war

build:
  tags:
    - runner
  image: docker:latest
  stage: build
  script:
    - echo hi
    - docker login -u tim0726 -p minseo0726
    - docker buildx build --help #--platform linux/amd64 --tag tim0726/kakaotest:0.1 .
    - docker push tim0726/kakaotest:0.1
    #docker run --name kakaotest -p 8080:8080 --link mariadb kakaotest:0.1
    #- ssh dorika@218.209.10.162