stages:
  - build

before_script:
  - docker info

build:
  tags:
    - runner
  image: docker:latest
  stage: build
  script:
    - ./gradlew bootWar
    - echo hi
    - docker build -t kakaotest:0.1 .
#