stages:
  - build-job
  - build
  - deploy
variables:
  IMAGE_NAME: tim0726/kakaotest:0.1


build-job:
 stage: build-job

 # Tag is identifier to select which gitlab-runner instance to use
 tags:
   - escare
 image: openjdk:11
 script:
   - ./gradlew bootWar
 cache:
   key: whenever-with-dependencies
   paths:
     - .gradle/wrapper
     - .gradle/caches
 artifacts:
   paths:
     - ./build/libs/app.war




docker-build-push:
 tags:
   - escare
 image: docker:latest
 stage: build
 script:
   - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
   - docker build -t tim0726/kakaotest:0.1 .
   - docker push tim0726/kakaotest:0.1



# ---------------------------------------------------------------------------------------- deployment -------------------------------------------------------------------- #

# This is deploying for DEVELOPMENT process, for testing.
# Using server is contributor dorika's personal server -- ubuntu 20.04 server.
deploy-DEV:
  tags:
    - escare
  only:
    - dev
  stage: deploy
  timeout: 3d
  before_script:
    - 'which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIV_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p $DEV_SERVER_PORT $DEV_SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh escare@$DEV_SERVER_IP -p $DEV_SERVER_PORT "cd skku/dev && nohup ./kuber.sh &"



# This is deploying for QA process, for testing.
# Using server is ESCARE server -- CentOS 7 server.
# Now(21.12.23) have connection issue, so use save server as DEVELOPMENT process.
deploy-QA:
  tags:
    - escare
  only:
    - QA
  stage: deploy
  timeout: 3d
  before_script:
    - 'which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIV_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p $QA_SERVER_PORT $QA_SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh escare@$QA_SERVER_IP -p $QA_SERVER_PORT "cd skku/qa && nohup ./kuber.sh &"



# This is deploying for PRODUCTION process, for testing.
# Using server is ESCARE server -- Ubuntu 20.04 server
# Now(21.12.23) have connection issue, so use save server as DEVELOPMENT process.
deploy-PROD:
  tags:
    - escare
  only:
    - main
  stage: deploy
  timeout: 3d
  before_script:
    - 'which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIV_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p $PROD_SERVER_PORT $PROD_SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh escare@$PROD_SERVER_IP -p $PROD_SERVER_PORT "cd skku/prod && nohup ./kuber.sh &"
