version: "3.0"
services:
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: kakaotest
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: on-failure
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
    links:
      - db
    depends_on:
      - db
#  app:
#    container_name: spring-app
#    image: adoptopenjdk/openjdk16
#    ports:
#      - 8080:8080
#    working_dir: /app
#    command:
#      - ./gradlew bootrun
#    restart: on-failure
#    depends_on:
#      - db